
const Data = [
    {
        "id": 0,
        "commonName": "Rose",
        "scientificName": "Rosa",
        "description": "Roses are perennial flowering plants known for their fragrant flowers and thorny stems. They come in a variety of colors, shapes, and sizes, making them popular in gardens and floral arrangements.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but well-drained",
          "temperature": "Prefers moderate temperatures (60-75°F)",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining, fertile soil with good organic content",
          "fertilization": "Feed regularly with balanced fertilizer during the growing season",
          "pruning": "Prune in late winter or early spring to promote new growth and shape the plant",
          "propagation": "Easily propagated through cuttings",
          "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-9",
          "nativeHabitat": "Various regions worldwide, including Europe, Asia, and North America",
          "uses": "Popular as ornamental plants in gardens, bouquets, and floral arrangements",
          "toxicity": "Non-toxic to humans, mildly toxic to pets if ingested",
          "pestsAndDiseases": "Susceptible to aphids, thrips, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://pardhuherbals.com/wp-content/uploads/2022/10/Rose-Plant.jpg"
      },
      {
        "id":1,
        "commonName": "Marigold",
        "scientificName": "Tagetes",
        "description": "Marigolds are annual flowering plants native to Mexico and Central America. They are known for their vibrant orange and yellow flowers, which bloom profusely throughout the summer and autumn.",
        "careRequirements": {
          "light": "Full sun (at least 6 hours of direct sunlight per day)",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed occasionally with balanced fertilizer for optimal growth",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or cuttings",
          "growingZones": "Suitable for USDA Zones 2-11, depending on the variety",
          "nativeHabitat": "Native to Mexico and Central America",
          "uses": "Popular as bedding plants, borders, and in containers",
          "toxicity": "Non-toxic to humans, pets, and most livestock",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by spider mites and aphids"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/76/118076-050-756CD4F5/French-marigold.jpg"
      },
      {
        "id": 2,
        "commonName": "Sunflower",
        "scientificName": "Helianthus annuus",
        "description": "Sunflowers are iconic annual flowering plants known for their large, daisy-like flowers and tall stems. They are native to North and South America and are cultivated for their seeds, which are a popular snack and a source of oil.",
        "careRequirements": {
          "light": "Full sun (at least 6-8 hours of direct sunlight per day)",
          "watering": "Regular watering, keeping soil consistently moist but not waterlogged",
          "temperature": "Prefers warm temperatures, frost-sensitive",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with balanced fertilizer during the growing season",
          "pruning": "Remove dead or damaged leaves and flowers as needed",
          "propagation": "Easily grown from seeds sown directly in the garden",
          "growingZones": "Suitable for USDA Zones 6-10",
          "nativeHabitat": "North and South America",
          "uses": "Grown for ornamental purposes, seeds, and oil production",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, caterpillars, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://hips.hearstapps.com/hmg-prod/images/sunforest-mix-sunflower-types-1586794598.jpg"
      },
      {
        "id": 3,
        "commonName": "Daisy",
        "scientificName": "Bellis perennis",
        "description": "Daisies are perennial flowering plants characterized by their white petals and yellow centers. They belong to the Asteraceae family and are native to Europe and Asia, though they have been naturalized in many other regions.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, allowing soil to dry out slightly between waterings",
          "temperature": "Prefers moderate temperatures, frost-resistant",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with moderate fertility",
          "fertilization": "Feed lightly with balanced fertilizer in spring",
          "pruning": "Deadhead spent flowers to promote continuous blooming",
          "propagation": "Easily propagated from seeds or division",
          "growingZones": "Suitable for USDA Zones 4-9",
          "nativeHabitat": "Europe and Asia",
          "uses": "Popular as bedding plants, borders, and in wildflower gardens",
          "toxicity": "Non-toxic to humans and pets",
          "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, slugs, and powdery mildew"
        },
        "type": "Outdoor",
        "images": "https://hips.hearstapps.com/hmg-prod/images/marguerite-daisy-types-1586981163.jpg"
      },
      {
        "id": 4,
        "commonName": "Tulip",
        "scientificName": "Tulipa",
        "description": "Tulips are bulbous perennial flowering plants native to Central Asia. They are known for their cup-shaped flowers in a wide range of colors and patterns. Tulips are popular ornamental plants and are often associated with the Netherlands.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, keeping soil evenly moist but not waterlogged",
          "temperature": "Prefers cool to moderate temperatures",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with bulb fertilizer in fall",
          "pruning": "Remove dead flowers and foliage after blooming",
          "propagation": "Propagate from bulbs",
          "growingZones": "Suitable for USDA Zones 3-8",
          "nativeHabitat": "Central Asia",
          "uses": "Popular as garden flowers, cut flowers, and for forcing indoors",
          "toxicity": "Non-toxic to humans, but bulbs can be toxic if ingested",
          "pestsAndDiseases": "Generally resistant to pests and diseases, but can be affected by aphids, slugs, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://m.media-amazon.com/images/I/71sQOlkixLL.jpg"
      },
      {
        "id": 5,
        "commonName": "Lily",
        "scientificName": "Lilium",
        "description": "Lilies are bulbous perennial flowering plants known for their large, showy flowers and pleasant fragrance. They belong to the Liliaceae family and are native to temperate regions of the Northern Hemisphere.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Regular watering, keeping soil evenly moist but not waterlogged",
          "temperature": "Prefers cool to moderate temperatures",
          "humidity": "Tolerates a wide range of humidity levels",
          "soil": "Well-draining soil with good fertility",
          "fertilization": "Feed with balanced fertilizer during the growing season",
          "pruning": "Remove spent flowers and foliage after blooming",
          "propagation": "Propagate from bulbs or seeds",
          "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-9",
          "nativeHabitat": "Temperate regions of the Northern Hemisphere",
          "uses": "Popular as garden flowers, cut flowers, and in floral arrangements",
          "toxicity": "Highly toxic to cats, mildly toxic to dogs and humans if ingested",
          "pestsAndDiseases": "Susceptible to aphids, thrips, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvjoslLCeNwFe6fESZOqgYfTUI9tCpRSweasu6kqK3nw&s"
      },
      {
        "id": 6,
        "commonName": "Geranium",
        "scientificName": "Pelargonium",
        "description": "Geraniums are flowering plants native to South Africa. They are popular ornamental plants grown for their colorful flowers and fragrant foliage. Geraniums are versatile and can be grown in gardens, containers, and hanging baskets.",
        "careRequirements": {
        "light": "Full sun to partial shade",
        "watering": "Regular watering, allowing soil to dry out slightly between waterings",
        "temperature": "Prefers moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with moderate fertility",
        "fertilization": "Feed with balanced fertilizer during the growing season",
        "pruning": "Pinch back spent flowers and leggy growth to promote bushiness",
        "propagation": "Propagate from stem cuttings or division",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 9-11",
        "nativeHabitat": "South Africa",
        "uses": "Popular as bedding plants, container plants, and in hanging baskets",
        "toxicity": "Mildly toxic to humans and pets if ingested",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://media.istockphoto.com/id/599751224/photo/red-garden-geranium-flowers-in-pot.jpg?s=612x612&w=0&k=20&c=R3FldsJr6O45zErYgs5IJv0tq9zJ_ualAcwAiS9LbmY="
        },
        {
        "id": 7,
        "commonName": "Hydrangea",
        "scientificName": "Hydrangea",
        "description": "Hydrangeas are deciduous or evergreen shrubs native to Asia and the Americas. They are known for their large, showy flower heads in shades of pink, blue, purple, and white. Hydrangeas are popular ornamental plants in gardens and landscapes.",
        "careRequirements": {
        "light": "Partial shade to full sun, depending on the variety",
        "watering": "Regular watering, keeping soil evenly moist",
        "temperature": "Prefers moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with good fertility",
        "fertilization": "Feed with balanced fertilizer in spring",
        "pruning": "Prune after flowering to remove dead wood and shape the plant",
        "propagation": "Propagate from stem cuttings or layering",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 3-9",
        "nativeHabitat": "Asia and the Americas",
        "uses": "Popular as garden shrubs, cut flowers, and in floral arrangements",
        "toxicity": "Mildly toxic to humans and pets if ingested",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, mites, and fungal diseases"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/21/137521-050-B20FDFCB/Flower-hydrangea-hortensia-French.jpg"
        },
        {
        "id": 8,
        "commonName": "Lavender",
        "scientificName": "Lavandula",
        "description": "Lavender is a fragrant perennial herb native to the Mediterranean region. It is known for its aromatic foliage and spikes of purple, blue, or pink flowers. Lavender is prized for its calming scent and is used in aromatherapy, culinary, and ornamental purposes.",
        "careRequirements": {
        "light": "Full sun",
        "watering": "Moderate watering, allowing soil to dry out slightly between waterings",
        "temperature": "Prefers warm temperatures, drought-tolerant once established",
        "humidity": "Tolerates low humidity levels",
        "soil": "Well-draining soil with low to moderate fertility",
        "fertilization": "Avoid heavy fertilization, as it can reduce fragrance",
        "pruning": "Prune after flowering to promote bushiness and remove spent flowers",
        "propagation": "Propagate from cuttings or seeds",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 5-9",
        "nativeHabitat": "Mediterranean region",
        "uses": "Popular for its fragrance in sachets, potpourri, cosmetics, and culinary dishes",
        "toxicity": "Non-toxic to humans, but can be toxic to pets if ingested in large quantities",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and root rot"
        },
        "type": "Outdoor",
        "images": "https://www.gardendesign.com/pictures/images/263x300Exact_68x0/site_3/english-lavender-lavandula-angustifolia-garden-design_11716.jpg"
        },
        {
        "id": 9,
        "commonName": "Snapdragon",
        "scientificName": "Antirrhinum majus",
        "description": "Snapdragons are colorful annual or perennial flowering plants native to Europe, North Africa, and North America. They are known for their unique, snap-like flowers that resemble the face of a dragon when squeezed. Snapdragons are popular in gardens and floral arrangements.",
        "careRequirements": {
        "light": "Full sun to partial shade",
        "watering": "Regular watering, keeping soil consistently moist but not waterlogged",
        "temperature": "Prefers cool to moderate temperatures",
        "humidity": "Tolerates a wide range of humidity levels",
        "soil": "Well-draining soil with moderate fertility",
        "fertilization": "Feed with balanced fertilizer during the growing season",
        "pruning": "Remove spent flowers to promote continuous blooming",
        "propagation": "Propagate from seeds or stem cuttings",
        "growingZones": "Depends on the variety, but most are suited for USDA Zones 4-10",
        "nativeHabitat": "Europe, North Africa, and North America",
        "uses": "Popular as bedding plants, borders, and in floral arrangements",
        "toxicity": "Non-toxic to humans and pets",
        "pestsAndDiseases": "Resistant to most pests and diseases, but can be affected by aphids, spider mites, and rust"
        },
        "type": "Outdoor",
        "images": "https://cdn.britannica.com/24/235424-050-9E128DEB/Snapdragon-flowers-plant.jpg"
        },
   

];
export default Data;