//  const suggestData = [
//     {
//         "id": 1,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "Jharkhand"
//       },
//       {
//         "id": 2,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "Jharkhand"
//       },
//       {
//         "id": 3,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "Jharkhand"
//       }, {
//         "id": 4,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images":"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "bihar"
//       },
//       {
//         "id": 5,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "bihar"
//       },
//       {
//         "id": 6,
//         "commonName": "Indian Jasmine",
//         "scientificName": "Jasminum sambac",
//         "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
//         "careRequirements": {
//           "light": "Full sun to partial shade",
//           "watering": "Keep soil consistently moist, especially during hot weather",
//           "temperature": "Thrives in warm temperatures between 70-90°F",
//           "humidity": "Prefers moderate to high humidity levels",
//           "soil": "Well-draining soil with organic matter",
//           "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
//           "pruning": "Prune after flowering to maintain shape and promote new growth",
//           "propagation": "Propagate from stem cuttings",
//           "growingZones": "Suitable for USDA Zones 9-11",
//           "nativeHabitat": "Native to India and other parts of South Asia",
//           "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
//           "toxicity": "Non-toxic",
//           "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
//         },
//         "images":"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
//         "type": "Outdoor",
//         "country": "India",
//         "state": "bihar"
//       },
// ];
// export default suggestData;

const suggestData = [
  {
    "id": 1,
    "commonName": "Elephant Foot Yam",
    "scientificName": "Amorphophallus paeoniifolius",
    "description": "Elephant Foot Yam is a tropical tuber crop found in Jharkhand, known for its edible corm and medicinal uses.",
    "careRequirements": {
      "light": "Partial shade to full sun",
      "watering": "Keep soil consistently moist but well-drained",
      "temperature": "Thrives in warm temperatures between 70-90°F",
      "humidity": "Prefers high humidity levels",
      "soil": "Rich, well-draining soil with organic matter",
      "fertilization": "Fertilize with organic compost during the growing season",
      "pruning": "Remove dead foliage regularly",
      "propagation": "Propagate from tuber cuttings",
      "growingZones": "Suitable for USDA Zones 10-12",
      "nativeHabitat": "Native to tropical Asia",
      "uses": "Used for food, traditional medicine, and ornamental purposes",
      "toxicity": "Non-toxic",
      "pestsAndDiseases": "Susceptible to aphids, nematodes, and fungal diseases"
    },
    "images": "https://imgs.search.brave.com/ZlpISfxPvsS9Wb9XeH1jZnRbgFrWb3oHvK74xu0Wi0E/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9qZXJy/eWNvbGVieXdpbGxp/YW1zLmZpbGVzLndv/cmRwcmVzcy5jb20v/MjAxNC8xMi9hbW9y/cGhvcGhhbGx1cy1l/bGVwaGFudC1mb290/LXlhbS00LmpwZWc_/dz0xMDAwJmg9ODE2",
    "type": "Outdoor",
    "country": "India",
    "state": "Jharkhand"
  },
  {
    "id": 2,
    "commonName": "Taro",
    "scientificName": "Colocasia esculenta",
    "description": "Taro is a tropical plant found in Jharkhand, cultivated for its edible starchy corms and leaves.",
    "careRequirements": {
      "light": "Partial shade to full sun",
      "watering": "Keep soil consistently moist",
      "temperature": "Thrives in warm temperatures between 70-95°F",
      "humidity": "Prefers high humidity levels",
      "soil": "Rich, well-draining soil",
      "fertilization": "Fertilize with a balanced fertilizer during the growing season",
      "pruning": "Remove yellow or dead leaves regularly",
      "propagation": "Propagate from corms or runners",
      "growingZones": "Suitable for USDA Zones 9-11",
      "nativeHabitat": "Native to Southeast Asia",
      "uses": "Used for food and ornamental purposes",
      "toxicity": "Non-toxic when cooked; raw plant parts can be toxic",
      "pestsAndDiseases": "Susceptible to aphids, spider mites, and fungal diseases"
    },
    "images": "https://imgs.search.brave.com/hSB4P5tbLKOAsW5yXEm_Nf5NG77pDuPYd0tshiOLiws/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNjM5/NDY0Njg0L3Bob3Rv/L3Rhcm8uanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPVRydnA1/M3pIUHdHVGtnM3VK/TDJDWHZiMGR2UDJk/aEdpeVc4MUNQY09y/Ymc9",
    "type": "Outdoor",
    "country": "India",
    "state": "Jharkhand"
  },
  {
    "id": 3,
    "commonName": "Indian Spinach",
    "scientificName": "Basella alba",
    "description": "Indian Spinach, also known as Malabar Spinach, is a fast-growing vine found in Jharkhand, used for its edible leaves.",
    "careRequirements": {
      "light": "Partial shade to full sun",
      "watering": "Keep soil consistently moist",
      "temperature": "Thrives in warm temperatures between 75-90°F",
      "humidity": "Prefers high humidity levels",
      "soil": "Rich, well-draining soil",
      "fertilization": "Fertilize monthly with a balanced fertilizer",
      "pruning": "Trim regularly to promote bushy growth",
      "propagation": "Propagate from seeds or cuttings",
      "growingZones": "Suitable for USDA Zones 10-12",
      "nativeHabitat": "Native to tropical Asia",
      "uses": "Used for food and ornamental purposes",
      "toxicity": "Non-toxic",
      "pestsAndDiseases": "Susceptible to aphids, caterpillars, and fungal diseases"
    },
    "images": "https://imgs.search.brave.com/96KsR6p8rRRr4NU8Lj1HgYhpNgplCEJbIG-NlBgLN4I/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/dGhlc3BydWNlLmNv/bS90aG1iL0dIeUFj/U0I3QmJkRHdxdHpP/ODJicHJRM1F5ST0v/MTUwMHgwL2ZpbHRl/cnM6bm9fdXBzY2Fs/ZSgpOm1heF9ieXRl/cygxNTAwMDApOnN0/cmlwX2ljYygpL2dy/b3dpbmctc3BpbmFj/aC0xNDAzNDQ4LTgt/MWNiNzFhOTQ2YjQ0/NDFjMGI1MjMxNjI5/OTFjNzU1NWEuanBn",
    "type": "Outdoor",
    "country": "India",
    "state": "Jharkhand"
  },
  {
    "id": 4,
    "commonName": "Bitter Gourd",
    "scientificName": "Momordica charantia",
    "description": "Bitter Gourd is a tropical vine found in Bihar, known for its edible and medicinally valuable bitter fruit.",
    "careRequirements": {
      "light": "Full sun",
      "watering": "Keep soil consistently moist",
      "temperature": "Thrives in warm temperatures between 70-90°F",
      "humidity": "Prefers high humidity levels",
      "soil": "Well-draining soil with organic matter",
      "fertilization": "Fertilize with a balanced fertilizer during the growing season",
      "pruning": "Prune to control vine growth and remove dead leaves",
      "propagation": "Propagate from seeds",
      "growingZones": "Suitable for USDA Zones 9-11",
      "nativeHabitat": "Native to tropical Asia",
      "uses": "Used for food and traditional medicine",
      "toxicity": "Non-toxic",
      "pestsAndDiseases": "Susceptible to aphids, whiteflies, and powdery mildew"
    },
    "images": "https://imgs.search.brave.com/XHdPNjbSfvsf0NgdaoNW0vd-W4bjW3DT0Mf4nZ2u1l4/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzA1/NzkvNzkyNC8wNTgw/L3QvMTgvYXNzZXRz/L3NodXR0ZXJzdG9j/a181ODY1NDI5ODAu/anBnP3Y9MTY2MTg3/MDAxMw",
    "type": "Outdoor",
    "country": "India",
    "state": "Bihar"
  },
  {
    "id": 5,
    "commonName": "Drumstick Plant",
    "scientificName": "Moringa oleifera",
    "description": "Drumstick Plant, also known as Moringa, is commonly grown in Bihar for its nutritious leaves, pods, and flowers.",
    "careRequirements": {
      "light": "Full sun",
      "watering": "Moderate watering; drought-tolerant once established",
      "temperature": "Thrives in warm temperatures between 75-95°F",
      "humidity": "Prefers moderate humidity levels",
      "soil": "Well-draining sandy or loamy soil",
      "fertilization": "Fertilize with organic compost annually",
      "pruning": "Prune to maintain size and promote new growth",
      "propagation": "Propagate from seeds or cuttings",
      "growingZones": "Suitable for USDA Zones 9-11",
      "nativeHabitat": "Native to South Asia",
      "uses": "Used for food, traditional medicine, and ornamental purposes",
      "toxicity": "Non-toxic",
      "pestsAndDiseases": "Susceptible to aphids, spider mites, and fungal diseases"
    },
    "images": "https://imgs.search.brave.com/HD730E4ajFzaMKxZnaE50fshPFwPIgSRN3lQs0eYibA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLmV0/c3lzdGF0aWMuY29t/LzE4ODkzMDA3L3Iv/aWwvYWE5MDdlLzE5/ODgwOTEzMjUvaWxf/NjAweDYwMC4xOTg4/MDkxMzI1XzZwbjcu/anBn",
    "type": "Outdoor",
    "country": "India",
    "state": "Bihar"
  },
  {
    "id": 6,
    "commonName": "Fenugreek",
    "scientificName": "Trigonella foenum-graecum",
    "description": "Fenugreek is a leafy herb found in Bihar, used for its seeds and leaves in cooking and traditional medicine.",
    "careRequirements": {
      "light": "Full sun to partial shade",
      "watering": "Keep soil consistently moist",
      "temperature": "Thrives in warm temperatures between 60-75°F",
      "humidity": "Prefers moderate humidity levels",
      "soil": "Well-draining soil with organic matter",
      "fertilization": "Fertilize lightly with compost or a balanced fertilizer",
      "pruning": "Harvest leaves regularly to encourage new growth",
      "propagation": "Propagate from seeds",
      "growingZones": "Suitable for USDA Zones 9-11",
      "nativeHabitat": "Native to the Mediterranean region",
      "uses": "Used for culinary and medicinal purposes",
      "toxicity": "Non-toxic",
      "pestsAndDiseases": "Susceptible to aphids, powdery mildew, and root rot"
    },
    "images": "https://imgs.search.brave.com/DwzXodjiVpHJ1xjHrx9m-dWlZ5020_9_XtFhlCnlkhA/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNDky/NzU3NjQ5L3Bob3Rv/L3Vuc3BlY2lmaWVk/LWZlbnVncmVlay1m/YWJhY2VhZS5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9Y0xZ/SDJ4Z0NadExuVkRM/TFhMeVdtWGx0ek1D/YkNub3laOWdYRjNj/QmN5TT0",
    "type": "Outdoor",
    "country": "India",
    "state": "Bihar"
  }
];
export default suggestData;
