 const suggestData = [
    {
        "id": 1,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "Jharkhand"
      },
      {
        "id": 2,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "Jharkhand"
      },
      {
        "id": 3,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "Jharkhand"
      }, {
        "id": 4,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images":"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "bihar"
      },
      {
        "id": 5,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "bihar"
      },
      {
        "id": 6,
        "commonName": "Indian Jasmine",
        "scientificName": "Jasminum sambac",
        "description": "Indian Jasmine, also known as Mogra, is a fragrant flowering plant native to South Asia. It produces small, white, highly fragrant flowers.",
        "careRequirements": {
          "light": "Full sun to partial shade",
          "watering": "Keep soil consistently moist, especially during hot weather",
          "temperature": "Thrives in warm temperatures between 70-90°F",
          "humidity": "Prefers moderate to high humidity levels",
          "soil": "Well-draining soil with organic matter",
          "fertilization": "Fertilize monthly during the growing season with a balanced fertilizer",
          "pruning": "Prune after flowering to maintain shape and promote new growth",
          "propagation": "Propagate from stem cuttings",
          "growingZones": "Suitable for USDA Zones 9-11",
          "nativeHabitat": "Native to India and other parts of South Asia",
          "uses": "Commonly used for religious ceremonies, perfumes, and ornamental purposes",
          "toxicity": "Non-toxic",
          "pestsAndDiseases": "Susceptible to aphids, scale insects, and fungal diseases"
        },
        "images":"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1684789715-the_sill-variant-white_gloss-zz_plant.jpg?crop=1xw:0.966xh;center,top&resize=980:*",
        "type": "Outdoor",
        "country": "India",
        "state": "bihar"
      },
];
export default suggestData;